### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tiefpunkt** [dlarue/KiCAD#1]
Hi @dlarue,

I really like this board, but I'd like to make some changes to it and put those changes back out into the world. What license are the design files released as, so I can do that properly?

Thanks,
Severin

**Comment by dlarue** [comment]
That's great!  What license would you like?  I'd only like to make sure the license is open for others and credit to the original design is included.  Mostly so they can find the original work.

**Comment by tiefpunkt** [comment]
CC-BY or CC-BY-SA are probably a good fit in terms of making sure your original design gets the credit it deserves. MIT is the easiest way but apart from in the license document, credit is optional in that case I think. Take a look at this: http://www.inmojo.com/licenses/
Let me know what you think, then I can prep a pull request

**Comment by tiefpunkt** [comment]
@dlarue what do you think, would CC-BY be ok for you?

**Comment by dlarue** [comment]
Thanks for pinging me on this and sorry about dropping the ball, I completely forgot about getting to this.  I just set the license to CC-BY-SA.  Seems the new owners of github removed the CC options in the GUI....

**Comment by tiefpunkt** [comment]
Sweet, thanks. I think GitHub doesn't offer it as an option in the normal selection view, as it shouldn't be applied to software, but it recognizes at least cc-by-sa-4.0. Any reason you went with 3.0? Otherwise we could update it, and it would tag the repo correctly.

**Comment by dlarue** [comment]
There were no CC options shown at all.  I had gone to CC site and got that reference to the license and figured it would have been the latest.  It's been updated.
